services:
  db:
    container_name: smart_move_mysql_container
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart_move_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: smart_move_redis_container
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart_move_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    container_name: smart_move_mailpit_container
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - smart_move_network

  app:
    container_name: smart_move_app_container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      MAIL_HOST: mailpit
    volumes:
      - ..:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - smart_move_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "composer install --no-interaction && php-fpm"

  nginx:
    container_name: smart_move_nginx_container
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smart_move_network
    depends_on:
      - app

  queue:
    container_name: smart_move_queue_container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      MAIL_HOST: mailpit
    volumes:
      - ..:/var/www/html
    networks:
      - smart_move_network
    depends_on:
      - app
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90

volumes:
  mysql_data:
  redis_data:


networks:
  smart_move_network:
    driver: bridge
