# CI/CD
name: CI

on:
  push:

    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f backend/docker/Dockerfile -t smart-move-app backend

      - name: Start app container
        run: docker run -d --name app -v ${{ github.workspace }}/backend:/var/www/html smart-move-app

      - name: Copy environment file
        run: docker exec app cp .env.example .env

      - name: Install Composer dependencies
        run: docker exec app composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: docker exec app php artisan key:generate

      #- name: Run Pint (code style check)
      #  run: docker exec app ./vendor/bin/pint --test

      - name: Run tests
        run: docker exec app php artisan test --compact
